{% set name = "libusdusb4" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: 534dff32adf7759450b11bb3360e875b476e9c6c71275879da0f9731f1c5ed80 

build:
  skip: True  # [win or osx]
  number: c867fbd2c732824f29ffec2b9744a0a28bfa1f7f1ce8ce5160ebcd5e84830797 1

about:
  home: https://www.usdigital.com
  summary: 'Software for  USB4 encoder box'
  description: |
    This is a shared library blob that is provided
    by US Digital for the USB4 encoder box
  doc_url: https://www.usdigital.com/products/accessories/interfaces/USB4
  dev_url: https://www.usdigital.com/products/accessories/interfaces/USB4

extra:
  recipe-maintainers:
    - valmar
    - chrisvam




